# Generated by Django 3.1.4 on 2021-01-06 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MW_STATS', '0004_auto_20210105_1706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friends',
            old_name='profile',
            new_name='user',
        ),
    ]
