# Generated by Django 3.1.4 on 2021-01-20 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MW_STATS', '0008_privateusers_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateusers',
            name='all_time_score',
            field=models.IntegerField(default=0),
        ),
    ]
