# Generated by Django 3.1.4 on 2021-02-05 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MW_STATS', '0009_privateusers_all_time_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='gamertag1',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='friends',
            name='gamertag2',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='friends',
            name='gamertag3',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='friends',
            name='gamertag4',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='friends',
            name='gamertag5',
            field=models.CharField(default='', max_length=30),
        ),
    ]
