# Generated by Django 3.1.4 on 2021-02-07 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MW_STATS', '0010_auto_20210205_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='gamertag1',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='friends',
            name='gamertag2',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='friends',
            name='gamertag3',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='friends',
            name='gamertag4',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='friends',
            name='gamertag5',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
